/**
 * @file Automatically generated by barrelsby.
 */

export * from "./IndexController";
export * from "./movies/Movie";
export * from "./movies/MovieMapper";
export * from "./movies/MoviesController";
